### ISSUE TITLE
Possible to release AesGcm code under MIT

### ISSUE THREAD

**Issue by ngarside** [trampster/Ropu#17]
I'm trying to use aesgcm on android and found this repo from [this thread](https://forums.xamarin.com/discussion/180017/aesgcm-support) on xamarin support. Unfortunately my project isn't compatible with the GPL. Would you be willing to release specifically the aesgcm code under an alternative license (e.g. MIT or BSD)? I totally understand if not.

**Comment by trampster** [comment]
Actually I did intend to extract it and release it under MIT after I got it working.

**Comment by trampster** [comment]
Long term I'd rather have mono implement it, can you add your support to https://github.com/mono/mono/issues/19285 so they will realise that people want it.

I'll reply to this with a link once I've created a new MIT licensed lib for it.

**Comment by ngarside** [comment]
Thank you, let me know if you want any assistance

**Comment by trampster** [comment]
I've made a start here: https://github.com/trampster/Ropu.AesGcm
Will test with Ropu tomorrow, and if all goes well you can try it out yourself.

**Comment by ngarside** [comment]
I've successfully tested this on Android 10, all seems to work fine. Thanks for releasing it 👍

**Comment by trampster** [comment]
Ropu.AesGcm has been published to nuget and Ropu has been updated to use it. I've tested it and it appears to work.

Thanks for giving me the push to do this.
