### ISSUE TITLE
Ropu.AesGcm NuGet without SSL lib

### ISSUE THREAD

**Issue by only4internet13** [trampster/Ropu#25]
Ropu.AesGcm NuGet does not have SSL lib (you have mentioned it there) but which ssl lib we need to include for it to work on iOS?
I want to use for iOS in Xamarin project.
Some guidance for different platforms would help as this looks a very promising NuGet.

**Comment by trampster** [comment]
This issue should be against https://github.com/trampster/Ropu.AesGcm.

However I havn't tried building OpenSSL for iOS, so I can't be much help here. You would have to google it.
